plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '1.0.14'
}

group = project.mod_group_id
version = project.mod_version

base {
    archivesName = project.mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21) // 1.21.1 uses Java 21
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven { url "https://www.cursemaven.com" }
}

dependencies {
    // Geckolib
    implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"

    // Dependencies
    implementation "curse.maven:dragons-survival-420799:7422257"
    implementation "curse.maven:corpse-316582:7018307"
    implementation "curse.maven:jade-324717:7545219"

    // DS addons
    implementation "curse.maven:tundra-dragon-dragon-survival-add-on-1246424:7678234"
    implementation "curse.maven:crystcursed-dragon-1379573:7627828"
    implementation "curse.maven:aether-dragon-dragon-survival-addon-1246018:6447148"
    //implementation "curse.maven:play-as-ender-dragon-dragon-survival-addon-1412806:7460661"
    //implementation "curse.maven:echo-sculk-dragon-for-dragon-survival-1252448:7240957"
    //implementation "curse.maven:frostfire-dragon-1469048:7662957"
    //implementation "curse.maven:dragonsurvival-revival-ancients-1251847:6523988"
    implementation "curse.maven:wing-kirin-1370041:7545026"
    implementation "curse.maven:dragon-survival-griffin-addon-1211879:6686273"
    implementation "curse.maven:be-bee-queen-dragon-survival-addon-1372834:7239335"
    implementation "curse.maven:desert-claw-dragon-survival-addon-1383729:7216235"
    implementation "curse.maven:astral-dragon-1252507:7056311"
    implementation "curse.maven:dragonlich-ds-addon-1245819:7690067"
    //implementation "curse.maven:tasanis-warden-dragon-1377155:7180529"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}